---
host: <your ip address>
user: admin
password: <your password>
tenant: infra
bridge_domain: default
dhcp_relay_policy: DhcpRelayP
dhcp_relay_label_scope: tenant
optional_args:
  providers:
  - epg_type: application_epg
    provider_detail:
      tenant: infra
      detail1: access
      detail2: default
    dhcp_server_address: 10.0.0.1
